import Foundation

// The vocabulary of the analysis (C3). A signal emits `Evidence`; the classifier
// combines evidence into a `Verdict`; the explainer renders the verdict's
// evidence into prose. Nothing here decides anything on its own.

enum Risk: String, Codable, Equatable { case safe, caution, danger }

// Categories are *outcomes* of the dominant signal, never declared by a path or a
// rule written for them. "duplicate version" is what you get when the version
// signal wins, not a scanner that looks for duplicate versions.
enum Category: String, Codable, Equatable {
    case cache, buildArtifact, diskImage, duplicateVersion, orphan, unknown

    var label: String {
        switch self {
        case .cache: return "Cache"
        case .buildArtifact: return "Build artifact"
        case .diskImage: return "Disk image"
        case .duplicateVersion: return "Duplicate version"
        case .orphan: return "Orphaned data"
        case .unknown: return "Large item"
        }
    }
}

enum Polarity: String, Codable, Equatable {
    case reclaimable    // evidence it is safe to remove
    case protective     // evidence it must be kept
    case neutral        // context, no weight toward either
}

// One piece of evidence: a polarity, a weight, and the human sentence that will be
// shown to the user verbatim. The `reason` is the only user-facing text the
// analysis produces, and it is written per-signal — never per-path.
struct Evidence: Codable, Equatable {
    let signal: String
    let polarity: Polarity
    /// 0…1. A protective evidence at or above `Evidence.vetoThreshold` forces
    /// `danger` regardless of any accumulated reclaimable weight.
    let weight: Double
    let reason: String
    /// The category this evidence argues for, when it wins. nil means it argues
    /// for no particular category.
    let category: Category?

    static let vetoThreshold = 1.0

    var isVeto: Bool { polarity == .protective && weight >= Evidence.vetoThreshold }
}

// A reached conclusion. `summary` is generated by the explainer from `evidence`;
// it is never assigned literal per-path copy.
struct Verdict: Codable, Equatable {
    let risk: Risk
    let category: Category
    let confidence: Double       // 0…1
    let evidence: [Evidence]     // ordered strongest-first
    let summary: String

    /// Only `safe` may ever be pre-selected (C3).
    var isPreselectable: Bool { risk == .safe }
}
